@startuml

component {
    control Richman
    Database DB <<bitable>>
    node Bill <<bitable>>
    Richman -down-> DB
}
component Wechat {
    node Subscription
}
component Feishu {
    node Bot
    node Event

    Bot .right.> Event:trigger


}
Event -up-> Richman:webhook
Richman -down-> Bill:OpenAPI
Richman -up-> Bot:OpenAPI

actor User

User -down-> Bot:send message
User -down-> Subscription:send message

Subscription -down-> Richman:webhook

@enduml